// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsDn-53ht_WVsw9wt8yDcJscn3s4wNpbc',
    appId: '1:405779507351:web:d6fc7b16c30b792ce761d2',
    messagingSenderId: '405779507351',
    projectId: 'car-f4670',
    authDomain: 'car-f4670.firebaseapp.com',
    storageBucket: 'car-f4670.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTEG_m5gXxQ259eSJAWcnyfEdDLmESeh8',
    appId: '1:405779507351:android:2108d7e60a12a618e761d2',
    messagingSenderId: '405779507351',
    projectId: 'car-f4670',
    storageBucket: 'car-f4670.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7BNYj_CYlznAjMMk4NysIjjdp1mZOwgo',
    appId: '1:405779507351:ios:3bb4016be81b0d05e761d2',
    messagingSenderId: '405779507351',
    projectId: 'car-f4670',
    storageBucket: 'car-f4670.appspot.com',
    iosClientId: '405779507351-0m8roh43rcuatl8f7hi7vsf81vln2hlf.apps.googleusercontent.com',
    iosBundleId: 'com.example.car',
  );
}
